# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73cfa253f1d1d711eac0346f07edac80c1c3a294436a4023440c763eda43c2e2d0f541f8ee3d3f51d97868b0977196f40f2a83cf91d4b17e7e8408a49088ed95

test:
  secret_key_base: 14f79f4c77be5783a789df98438cdd7b60790ab37e950bd4c21d48732cb878ada92cddac0ef700b9b2a8fc660d53c52b9e8b261306402d868b01a1dee2dd67f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
